AWSTemplateFormatVersion: "2010-09-09"
Description: "AI Video Clipper - AWS CloudFormation Template for GPU EC2 Deployment"

Parameters:
  InstanceType:
    Description: EC2 GPU instance type
    Type: String
    Default: g4dn.xlarge
    AllowedValues:
      - g4dn.xlarge
      - g4dn.2xlarge
      - g4dn.4xlarge
      - g5.xlarge
      - g5.2xlarge
      - p3.2xlarge
    ConstraintDescription: Must be a valid GPU instance type

  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair

  VolumeSize:
    Description: Size of the EBS volume in GB
    Type: Number
    Default: 100
    MinValue: 50
    MaxValue: 500

  AllowedSSHIP:
    Description: IP address allowed for SSH access (CIDR notation)
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: ^(\d{1,3}\.){3}\d{1,3}/\d{1,2}$

  GroqAPIKey:
    Description: Groq API Key for fallback transcription (optional)
    Type: String
    Default: ""
    NoEcho: true

Mappings:
  RegionAMI:
    us-east-1:
      AMI: ami-0c7217cdde317cfec # Ubuntu 22.04 LTS
    us-west-2:
      AMI: ami-03f65b8614a860c29
    eu-west-1:
      AMI: ami-0905a3c97561e0b69
    ap-southeast-1:
      AMI: ami-078c1149d8ad719a7
    ap-northeast-1:
      AMI: ami-07c589821f2b353aa

Resources:
  # Security Group
  ClipperSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for AI Video Clipper
      GroupName: clipper-security-group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHIP
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
          Description: Flask API
      Tags:
        - Key: Name
          Value: clipper-security-group

  # IAM Role for EC2
  ClipperInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: clipper-instance-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: ClipperS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${ClipperS3Bucket}"
                  - !Sub "arn:aws:s3:::${ClipperS3Bucket}/*"

  ClipperInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref ClipperInstanceRole

  # S3 Bucket for storage
  ClipperS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "ai-video-clipper-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldClips
            Status: Enabled
            ExpirationInDays: 30
            Prefix: outputs/
      Tags:
        - Key: Application
          Value: AI-Video-Clipper

  # EC2 Instance
  ClipperInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap [RegionAMI, !Ref "AWS::Region", AMI]
      IamInstanceProfile: !Ref ClipperInstanceProfile
      SecurityGroupIds:
        - !Ref ClipperSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp3
            Iops: 3000
            Throughput: 125
            DeleteOnTermination: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e

          # Log output
          exec > >(tee /var/log/user-data.log) 2>&1

          echo "=== Starting AI Video Clipper Setup ==="

          # Update system
          apt-get update && apt-get upgrade -y

          # Install dependencies
          apt-get install -y python3 python3-pip python3-venv ffmpeg git curl wget nginx

          # Install NVIDIA drivers
          apt-get install -y nvidia-driver-535 nvidia-cuda-toolkit

          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

          # Clone repository
          cd /home/ubuntu
          git clone https://github.com/astika327-dev/clipping.git
          chown -R ubuntu:ubuntu clipping

          # Setup Python
          cd clipping
          python3 -m venv venv
          source venv/bin/activate

          cd backend
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

          # Create .env
          cp .env.example .env
          sed -i 's/GROQ_API_KEY=/GROQ_API_KEY=${GroqAPIKey}/' .env

          mkdir -p uploads outputs

          # Build frontend
          cd ../frontend
          npm install
          npm run build

          # Setup systemd service
          cat > /etc/systemd/system/clipper-backend.service << 'EOF'
          [Unit]
          Description=AI Video Clipper Backend
          After=network.target

          [Service]
          Type=simple
          User=ubuntu
          WorkingDirectory=/home/ubuntu/clipping/backend
          Environment="PATH=/home/ubuntu/clipping/venv/bin:/usr/bin"
          ExecStart=/home/ubuntu/clipping/venv/bin/python app.py --production --port 5000
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
          EOF

          systemctl daemon-reload
          systemctl enable clipper-backend
          systemctl start clipper-backend

          # Configure Nginx
          cat > /etc/nginx/sites-available/clipper << 'NGINX'
          server {
              listen 80;
              server_name _;
              
              location / {
                  root /home/ubuntu/clipping/frontend/dist;
                  try_files $uri $uri/ /index.html;
              }
              
              location ~ ^/(upload|process|status|download|clips|storage|system|health|youtube|api) {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_connect_timeout 600;
                  proxy_send_timeout 600;
                  proxy_read_timeout 600;
                  client_max_body_size 5G;
              }
          }
          NGINX

          ln -sf /etc/nginx/sites-available/clipper /etc/nginx/sites-enabled/
          rm -f /etc/nginx/sites-enabled/default
          nginx -t && systemctl restart nginx

          echo "=== Setup Complete ==="

      Tags:
        - Key: Name
          Value: AI-Video-Clipper

  # Elastic IP
  ClipperElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref ClipperInstance
      Tags:
        - Key: Name
          Value: clipper-elastic-ip

Outputs:
  InstanceId:
    Description: Instance ID
    Value: !Ref ClipperInstance

  PublicIP:
    Description: Public IP address
    Value: !Ref ClipperElasticIP

  WebsiteURL:
    Description: Application URL
    Value: !Sub "http://${ClipperElasticIP}"

  APIURL:
    Description: API Endpoint
    Value: !Sub "http://${ClipperElasticIP}:5000"

  SSHCommand:
    Description: SSH connection command
    Value: !Sub "ssh -i ${KeyName}.pem ubuntu@${ClipperElasticIP}"

  S3Bucket:
    Description: S3 bucket for storage
    Value: !Ref ClipperS3Bucket
